- name: install redis component
  hosts: redis
  become: 'yes'
  tasks:
    - name: install redis repo
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: 'yes'

    - name: Enable Redis 6.2 from package streams
      ansible.builtin.command: yum module enable redis:remi-6.2 -y

    - name: install redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: remote connections to redis
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start & Enable Redis Service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: 'yes'
